<h1>Notebook para Streptosporangiaceae </h1>

In [3]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import hamming
import gudhi as gd
import seaborn as sns
from statistics import mode
import multiprocessing
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import gudhi as gd
# from scipy.spatial.distance import hamming
import plotly.graph_objs as go
import networkx as nx
import plotly.graph_objects as go
import plotly.io as pio
from networkx.utils import not_implemented_for, pairwise
from concurrent.futures import ThreadPoolExecutor, as_completed
import plotly
import plotly.express as px
from module_functions import *

<h2>Se extrae la información </h2>

In [4]:
info=pd.read_csv('data/pscpStrepto.blast',sep='\t',header=None)

names=pd.read_csv('data/Strepto.ids',sep='\t',dtype='object',header=None)

<h2>Se crean los data frames</h2>

In [5]:
df_by_pathway,df_by_pathway_drop_duplicate,representative_genomes=get_df_by_pathway(info)

In [ ]:
print('n genomas:',len(df_by_pathway['3PGA_AMINOACIDS'].index))
cont=0
cont2=0
for i,j in df_by_pathway.items():
    cont2+=len(j.columns)
    cont+=1
    print(i)
print('n rutas',cont)
print('n genes',cont2)

<h2> Se crea el complejo simplicial</h2>

In [19]:
complex_pathways=get_complex_by_pathways(df_by_pathway_drop_duplicate)

In [ ]:
#plot_all_bar_code_pathways(complex_pathways)

<h2>Se buscan los uno hoyos</h2>

In [454]:
holes_by_pathway=holes_pathway_strepto()
holes_by_pathway['\ufeffGlycolysis']=[]

In [455]:
holes_with_names=change_vertex_to_code_per_path(holes_by_pathway,df_by_pathway_drop_duplicate)

In [461]:
resum=get_resum_df(df_by_pathway,representative_genomes,names,complex_pathways,holes_with_names).drop(index='\ufeffGlycolysis')
resum

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
E4P_AMINO_ACIDS,19,109,[[[Herbidospora cretacea strain NRRL B-16917 J...,"[[[Herbidospora, Herbidospora, Herbidospora, H...","[1.0, 2.0]"
3PGA_AMINOACIDS,6,133,"[[[Microbispora sp. H10670 JABBWW010000001.1, ...","[[[Microbispora, Microbispora, Microbispora, M...",[1.0]
OXALACETATE_AMINOACIDS,19,163,[[[Microbispora rosea subsp. nonnitritogenes s...,"[[[Microbispora, Microbispora, Microbispora, M...","[1.0, 2.0, 3.0]"
TCA,11,99,"[[[Microbispora sp. ATCC PTA-5024 KI866522.1, ...","[[[Microbispora, Streptosporangium, Microbispo...","[1.0, 2.0]"
Glycolysis,10,111,[[[Microbispora rosea subsp. nonnitritogenes s...,"[[[Microbispora, Microbispora, Microbispora, M...",[1.0]
ALPHAKETOGLUTARATE_AMINOACIDS,15,112,"[[[Streptosporangium sp. caverna CP029711.1, S...","[[[Streptosporangium, Streptosporangium], [Mic...","[1.0, 2.0]"
PPP,8,97,[[Streptosporangiaceae bacterium JOPF063 JASHQ...,"[[Streptosporangiaceae, Streptosporangiaceae, ...",[1.0]
PYR_THR_AA,10,112,"[[[Nonomuraea coxensis DSM 45129 KB903939.1, N...","[[[Nonomuraea, Nonomuraea, Nonomuraea, Nonomur...",[1.0]
R5P_AMINOACIDS,10,71,"[[[Thermobispora bispora DSM 43833 CP001874.1,...","[[[Thermobispora, Thermobispora, Microbispora,...",[1.0]

In [494]:
generos=set()
for i in traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index:
    generos.add(i.split(' ')[0])
df_count_genomes=pd.DataFrame(index=generos)
df_count_genomes['conteo']=0
for path in resum.index:
    ciclos_path=resum.loc[path,'ciclos por genero']
    for cic in ciclos_path:
        for vert in cic:
            if type(vert)==str:
                df_count_genomes.loc[vert,'conteo']=df_count_genomes.loc[vert,'conteo']+1
            else:
                for i in vert:
                    df_count_genomes.loc[i,'conteo']=df_count_genomes.loc[i,'conteo']+1
(df_count_genomes.sort_values(by='conteo',ascending=False)/df_count_genomes.sum())*100

                         conteo
Nonomuraea            23.261725
Microbispora          19.443268
Streptosporangiaceae  14.475038
Streptosporangium      8.889561
Sphaerisporangium      6.729198
Planomonospora         4.302572
Herbidospora           3.993949
Thermobispora          3.225416
Planobispora           3.110439
Microtetraspora        2.977307
Planotetraspora        2.783661
Acrocarpospora         1.416036
Spongiactinospora      1.295008
Sinosporangium         0.980333
Thermoactinospora      0.720121
Thermopolyspora        0.677761
Bailinhaonella         0.520424
Rhizohabitans          0.508321
Thermocatellispora     0.290469
Sphaerimonospora       0.266263
Actinomadura           0.084720
Acidimicrobium         0.048411

In [519]:
generos=set()
for i in traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index:
    generos.add(i.split(' ')[0])
df_count_genomes=pd.DataFrame(index=traduced_df(df_by_pathway['R5P_AMINOACIDS'],names).index)
df_count_genomes['conteo']=0
for path in resum.index:
    ciclos_path=resum.loc[path,'ciclos']
    for cic in ciclos_path:
        for vert in cic:
            if type(vert)==str:
                df_count_genomes.loc[vert,'conteo']=df_count_genomes.loc[vert,'conteo']+1
            else:
                for i in vert:
                    df_count_genomes.loc[i,'conteo']=df_count_genomes.loc[i,'conteo']+1
df_count_genomes.sort_values(by='conteo',ascending=False).head(6)

                                                    conteo
R5P_AMINOACIDS
Microbispora rosea subsp. nonnitritogenes strai...     134
Microbispora rosea subsp. nonnitritogenes strai...     134
Thermobispora bispora DSM 43833 sequence NC_014...      87
Thermobispora bispora DSM 43833 CP001874.1              87
Thermobispora bispora strain ZC4 NZ_CP039124.1          86
Thermobispora bispora strain ZC4 CP039124.1             86

In [518]:
long=[]
for k in resum.index:
    for i in resum.loc[k,'ciclos']:
        long.append(len(i))
print(set(long))
long.count(6)

{4, 5, 6, 7, 8, 9, 10, 11}

47

In [490]:
generos=set()
for i in traduced_df(df_by_pathway['PPP'],names).index:
    generos.add(i.split(' ')[0])

In [491]:
generos

{'Acidimicrobium',
 'Acrocarpospora',
 'Actinomadura',
 'Bailinhaonella',
 'Herbidospora',
 'Microbispora',
 'Microtetraspora',
 'Nonomuraea',
 'Planobispora',
 'Planomonospora',
 'Planotetraspora',
 'Rhizohabitans',
 'Sinosporangium',
 'Sphaerimonospora',
 'Sphaerisporangium',
 'Spongiactinospora',
 'Streptosporangiaceae',
 'Streptosporangium',
 'Thermoactinospora',
 'Thermobispora',
 'Thermocatellispora',
 'Thermopolyspora'}

In [487]:
names[names[2]=='Microbispora rosea subsp. nonnitritogenes strain NRRL B-2631']

,0,1,2
190,1350627,6666666.1069792,Microbispora rosea subsp. nonnitritogenes stra...
531,1350284,6666666.1069449,Microbispora rosea subsp. nonnitritogenes stra...

In [480]:
(df_count_genomes.sort_values(by='conteo',ascending=False)/df_count_genomes.sum()*100).sum()

conteo    100.0
dtype: float64

In [468]:
df_count_genomes=pd.DataFrame(index=traduced_df(df_by_pathway['PPP'],names).index)
df_count_genomes['conteo']=0

In [471]:
df_count_genomes.loc['Streptosporangium roseum DSM 43021 CP001814.1','conteo']=df_count_genomes.loc['Streptosporangium roseum DSM 43021 CP001814.1','conteo']+1

<h2>Se ven los elementos que hacen el hoyo</h2>

In [256]:
df_pathway_make_hole=get_df_by_pathway_make_hole_droped_cols(df_by_pathway_drop_duplicate,holes_with_names)
df_count_genes_participation=pd.DataFrame()
for path in df_pathway_make_hole.keys():
    print('los genes que participan en los 1-hoyos para',path,'son:')
    genes=[]
    for df in df_pathway_make_hole[path]:
        genes.extend(list(df.columns))
    set_count_genes=set()
    for gen in genes:
        df_count_genes_participation.loc[gen,'conteo']=genes.count(gen)
        df_count_genes_participation.loc[gen,'ruta']=path
        set_count_genes.add(gen+':'+str(genes.count(gen)))
    print(str(set_count_genes))

los genes que participan en los 1-hoyos para E4P_AMINO_ACIDS son:
{'3_dehydroquinate_dehydratase:27', '3_phosphoshikimate_1carboxyvinyltransferase:43', 'bifunctional_indole3glycerol_phosphate_synthase_phosphoribosylanthranilate_isomerase:20', 'Indole3glycerol_phosphate_synthase:18', 'Tryptophan_synthase_alpha:44', 'Prephenate_dehydratase:39', 'Shikimate_kinase:38', 'Aspartate_amino_transferase:94', 'Prephenate_dehydrogenase:59', 'Anthranilate_synthase_component_1:69', 'phosphoribosylanthranilate_isomerase:39', 'Chorismate_mutase:42', 'Tryptophan_synthase_beta:62', 'Anthranilate_phosphoribosyltransferase:54', 'Chorismate_synthase:50', 'Shikimate_dehydrogenase:59', 'Phosphoribosyl_isomerase:41', '3_dehydroquinate_synthase:33', '2_dehydro_3_deoxyphosphoheptonate_aldolase:50'}
los genes que participan en los 1-hoyos para 3PGA_AMINOACIDS son:
{'Phosphoglycerate_dehydrogenase:97', 'Phosphoserine_aminotransferase:19', 'Cysteine_synthase:72', 'glycine_hydroxymethyltransferase:68', 'serine_O_acetyltransferase:17', 'Phosphoserine_Phosphatase:32'}
los genes que participan en los 1-hoyos para ﻿Glycolysis son:
set()
los genes que participan en los 1-hoyos para OXALACETATE_AMINOACIDS son:
{'Homoserine_dehydrogenase:43', 'Tetrahydrodipicolinate_N_succinyl_transferase:77', 'Aspartate_semialdehyde_dehydrogenase:38', 'Aspartate_transaminase:133', 'diaminopimelate_epimerase:62', 'Homoserine_O_succinyltransferase:80', 'cystathione_gamma_synthetase:109', 'Asparagine_synthase:129', 'Homoserine_kinase:44', 'Methionine_synthase:115', 'succinyldiaminopimelate_transaminase:131', 'succinyl_diaminopimelate_desuccinylase:43', 'cystathione_beta_lyase:132', 'Aspartate_kinase:45', 'Threonine_synthase:111', 'diaminopimelate_decarboxylase:116', 'dihydropicolinate_synthase:138', 'argininosuccinate_lyase:56', 'dihydropicolinate_reductase:40'}
los genes que participan en los 1-hoyos para TCA son:
{'fumarate_reductase_ironsulfur_subunit:43', 'Aconitate_hydratase:59', 'dihydrolipoamide_acetyltransferase:62', 'alphaketoglutarate_decarboxylase:23', 'malate_dehydrogenase:20', 'succinylCoA_synthetase_subunit_beta:34', 'succinylCoA_synthetase_subunit_alpha:37', 'Isocitrate_dehydrogenase:19', 'fumarate_hydratase:43', 'Succinate_dehydrogenase_flavoprotein:65', 'Citrate_synthase:42'}
los genes que participan en los 1-hoyos para Glycolysis son:
{'Pyruvate_kinase:14', 'Triosephosphate_isomerase:20', 'glyceraldehyde3phosphate_dehydrogenase:56', 'enolase:34', 'Glucose_6_phosphate_isomerase:45', 'Glucose_kinase:95', 'Fructose_biphosphate_aldolase:20', 'phosphoglycerate_mutase:41', 'phosphoglycerate_kinase:39', 'Phosphofructokinase:57'}
los genes que participan en los 1-hoyos para ALPHAKETOGLUTARATE_AMINOACIDS son:
{'Acetylornithine_aminotransferase:96', 'glutamate:54', 'N-acetyl-gamma-glutamyl-phosphate_reductase:41', 'glutamate_synthase:42', 'Glutamine_synthetase:80', 'Glutamine_2-oxoglutarate:48', 'Acetylglutamate_kinase:25', 'N-acetylglutamate_synthase:24', 'Argininosuccinate:45', 'Ornithine_carbamoyltransferase:51', 'Glutamate_N-acetyltransferase:24', 'argininosuccinate_lyase:41', 'Glutamate-5-semialdehyde_dehydrogenase:35', 'Pyrroline-5-carboxylate_reductase:31', 'Glutamate_5_kinase:36'}
los genes que participan en los 1-hoyos para PPP son:
{'phosphogluconate_dehydrogenase:49', 'Ribose_5_phosphate_isomerase:34', 'transketolaseA:57', '6_phosphogluconolactonase:17', 'transaldolase:24', 'Ribulose_phosphate_3_epimerase:21', 'transketolase:24', 'Glucose_6_phosphate_dehydrogenase:70'}
los genes que participan en los 1-hoyos para PYR_THR_AA son:
{'Acetolactate_synthase_large_subunit:101', '3isopropylmalate_dehydrogenase:58', 'Isopropyl_malate_synthase:55', 'Threonine_ammonialiase:77', 'Dihydroxiacid_dehydratase:79', 'isopropylmalate_isomerase_small_subunit:30', 'Branchedchain_amino_acid_transaminase:47', 'isopropylmalate_isomerase_large_subunit:36', 'Alanine_dehydrogenase:49', 'Ketoacid_reductoisomerase:29'}
los genes que participan en los 1-hoyos para R5P_AMINOACIDS son:
{'imidazoleglycerol_phosphate_dehydratase:15', 'ATP_phosphoribosyltransferase:24', 'phosphoribosyl_ATP_diphosphatase:11', 'histidinolphosphate_aminotransferase:40', 'phosphoribosyl_AMP_cyclohydrolase:10', 'ribosephosphate_pyrophosphokinase:34', 'histidinol_dehydrogenase:18', 'imidazole_glycerol_phosphate_synthase_H:16', 'histidinol_phosphatase:17', 'phosphoribosyl_isomerase_A:13'}

In [257]:
total=df_count_genes_participation.sum()['conteo']
df_count_genes_participation.sort_values(by='conteo',ascending=False,inplace=True)

In [37]:
for i in df_count_genes_participation.index:
    print(i,df_count_genes_participation.loc[i,].values[0])

dihydropicolinate_synthase 138.0
Aspartate_transaminase 133.0
cystathione_beta_lyase 132.0
succinyldiaminopimelate_transaminase 131.0
Asparagine_synthase 129.0
diaminopimelate_decarboxylase 116.0
Methionine_synthase 115.0
Threonine_synthase 111.0
cystathione_gamma_synthetase 109.0
Acetolactate_synthase_large_subunit 101.0
Phosphoglycerate_dehydrogenase 97.0
Acetylornithine_aminotransferase 96.0
Glucose_kinase 95.0
Aspartate_amino_transferase 94.0
Glutamine_synthetase 80.0
Homoserine_O_succinyltransferase 80.0
Dihydroxiacid_dehydratase 79.0
Tetrahydrodipicolinate_N_succinyl_transferase 77.0
Threonine_ammonialiase 77.0
Cysteine_synthase 72.0
Glucose_6_phosphate_dehydrogenase 70.0
Anthranilate_synthase_component_1 69.0
glycine_hydroxymethyltransferase 68.0
Succinate_dehydrogenase_flavoprotein 65.0
diaminopimelate_epimerase 62.0
dihydrolipoamide_acetyltransferase 62.0
Tryptophan_synthase_beta 62.0
Prephenate_dehydrogenase 59.0
Shikimate_dehydrogenase 59.0
Aconitate_hydratase 59.0
3isopropylmalate_dehydrogenase 58.0
Phosphofructokinase 57.0
transketolaseA 57.0
glyceraldehyde3phosphate_dehydrogenase 56.0
Isopropyl_malate_synthase 55.0
Anthranilate_phosphoribosyltransferase 54.0
glutamate 54.0
Ornithine_carbamoyltransferase 51.0
2_dehydro_3_deoxyphosphoheptonate_aldolase 50.0
Chorismate_synthase 50.0
Alanine_dehydrogenase 49.0
phosphogluconate_dehydrogenase 49.0
Glutamine_2-oxoglutarate 48.0
Branchedchain_amino_acid_transaminase 47.0
Aspartate_kinase 45.0
Argininosuccinate 45.0
Glucose_6_phosphate_isomerase 45.0
Homoserine_kinase 44.0
Tryptophan_synthase_alpha 44.0
fumarate_reductase_ironsulfur_subunit 43.0
succinyl_diaminopimelate_desuccinylase 43.0
fumarate_hydratase 43.0
Homoserine_dehydrogenase 43.0
3_phosphoshikimate_1carboxyvinyltransferase 43.0
Chorismate_mutase 42.0
glutamate_synthase 42.0
Citrate_synthase 42.0
Phosphoribosyl_isomerase 41.0
N-acetyl-gamma-glutamyl-phosphate_reductase 41.0
phosphoglycerate_mutase 41.0
argininosuccinate_lyase 41.0
dihydropicolinate_reductase 40.0
histidinolphosphate_aminotransferase 40.0
Prephenate_dehydratase 39.0
phosphoribosylanthranilate_isomerase 39.0
phosphoglycerate_kinase 39.0
Shikimate_kinase 38.0
Aspartate_semialdehyde_dehydrogenase 38.0
succinylCoA_synthetase_subunit_alpha 37.0
isopropylmalate_isomerase_large_subunit 36.0
Glutamate_5_kinase 36.0
Glutamate-5-semialdehyde_dehydrogenase 35.0
enolase 34.0
Ribose_5_phosphate_isomerase 34.0
succinylCoA_synthetase_subunit_beta 34.0
ribosephosphate_pyrophosphokinase 34.0
3_dehydroquinate_synthase 33.0
Phosphoserine_Phosphatase 32.0
Pyrroline-5-carboxylate_reductase 31.0
isopropylmalate_isomerase_small_subunit 30.0
Ketoacid_reductoisomerase 29.0
3_dehydroquinate_dehydratase 27.0
Acetylglutamate_kinase 25.0
Glutamate_N-acetyltransferase 24.0
N-acetylglutamate_synthase 24.0
ATP_phosphoribosyltransferase 24.0
transaldolase 24.0
transketolase 24.0
alphaketoglutarate_decarboxylase 23.0
Ribulose_phosphate_3_epimerase 21.0
Triosephosphate_isomerase 20.0
Fructose_biphosphate_aldolase 20.0
malate_dehydrogenase 20.0
bifunctional_indole3glycerol_phosphate_synthase_phosphoribosylanthranilate_isomerase 20.0
Isocitrate_dehydrogenase 19.0
Phosphoserine_aminotransferase 19.0
histidinol_dehydrogenase 18.0
Indole3glycerol_phosphate_synthase 18.0
6_phosphogluconolactonase 17.0
serine_O_acetyltransferase 17.0
histidinol_phosphatase 17.0
imidazole_glycerol_phosphate_synthase_H 16.0
imidazoleglycerol_phosphate_dehydratase 15.0
Pyruvate_kinase 14.0
phosphoribosyl_isomerase_A 13.0
phosphoribosyl_ATP_diphosphatase 11.0
phosphoribosyl_AMP_cyclohydrolase 10.0

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

# Datos para las diferentes especies
data_cyanobacteria = {
    'Acetylornithine_aminotransferase': 42.0,
    'Glutamine_synthetase': 37.0,
    'Anthranilate_synthase_component_1': 35.0,
    '3_dehydroquinate_synthase': 34.0,
    'Indole3glycerol_phosphate_synthase': 33.0,
    'imidazole_glycerol_phosphate_synthase_H': 32.0,
    'phosphoribosyl_isomerase_A': 31.0,
    'histidinol_dehydrogenase': 28.0,
    'ribosephosphate_pyrophosphokinase': 24.0,
    'Acetolactate_synthase_large_subunit': 24.0,
    'Aspartate_transaminase': 24.0,
    '3isopropylmalate_dehydrogenase': 23.0,
    'Tryptophan_synthase_beta': 23.0,
    'Glutamate_5_semialdehyde_dehydrogenase': 23.0,
    'imidazoleglycerol_phosphate_dehydratase': 22.0,
    'glutamate_synthase': 20.0,
    'Anthranilate_phosphoribosyltransferase': 20.0,
    'Threonine_synthase': 19.0,
    'Pyrroline_5_carboxylate_reductase': 18.0,
    'isopropylmalate_isomerase_large_subunit': 18.0,
    'N_acetyl_gamma_glutamyl_phosphate_reductase': 18.0,
    'phosphoribosylanthranilate_isomerase': 17.0,
    'diaminopimelate_decarboxylase': 16.0,
    'Dihydroxiacid_dehydratase': 16.0,
    'glutamate_dehydrogenase': 14.0,
    'Ketoacid_reductoisomerase': 14.0,
    'Argininosuccinate_synthase': 13.0,
    'Tryptophan_synthase_alpha': 13.0,
    'dihydropicolinate_synthase': 12.0,
    'argininosuccinate_lyase': 12.0,
    'Glutamine_2_oxoglutarate_aminotransferase': 10.0,
    'Acetylglutamate_kinase': 9.0,
    'N_acetylglutamate_synthase': 9.0,
    'enolase': 9.0,
    'Pyruvate_kinase': 8.0,
    'Ornithine_carbamoyltransferase': 7.0,
    'glycine_hydroxymethyltransferase': 7.0,
    'Cysteine_synthase': 7.0,
    'Citrate_synthase': 6.0,
    'phosphoglycerate_kinase': 5.0,
    'fumarate_reductase_ironsulfur_subunit': 4.0,
    'fumarate_hydratase': 4.0
}

data_ornithinimicrobiaceae = {
    'Acetylornithine_aminotransferase': 3.0,
    'glutamate_synthase': 3.0,
    '3isopropylmalate_dehydrogenase': 2.0,
    'Aspartate_transaminase': 2.0,
    'Alanine_dehydrogenase': 2.0,
    'succinyldiaminopimelate_transaminase': 2.0,
    'Homoserine_O_succinyltransferase': 2.0,
    'Dihydroxiacid_dehydratase': 2.0,
    'phosphogluconate_dehydrogenase': 2.0,
    'Ketoacid_reductoisomerase': 2.0,
    'ribosephosphate_pyrophosphokinase': 1.0,
    'histidinolphosphate_aminotransferase': 1.0,
    'glycine_hydroxymethyltransferase': 1.0,
    'Phosphoglycerate_dehydrogenase': 1.0,
    'phosphoglycerate_mutase': 1.0,
    'Cysteine_synthase': 1.0,
    'imidazole_glycerol_phosphate_synthase_H': 1.0,
    'Threonine_ammonialiase': 1.0,
    'Isopropyl_malate_synthase': 1.0,
    'isopropylmalate_isomerase_large_subunit': 1.0,
    'Acetolactate_synthase_large_subunit': 1.0,
    'phosphoribosyl_AMP_cyclohydrolase': 1.0,
    'Citrate_synthase': 1.0,
    'ATP_phosphoribosyltransferase': 1.0,
    'fumarate_hydratase': 1.0,
    'Glucose_kinase': 1.0,
    'Aconitate_hydratase': 1.0,
    'glutamate': 1.0,
    '6_phosphogluconolactonase': 1.0,
    'Glucose_6_phosphate_dehydrogenase': 1.0,
    'Ribose_5_phosphate_isomerase': 1.0,
    'Asparagine_synthase': 1.0,
    'cystathione_beta_lyase': 1.0,
    'argininosuccinate_lyase': 1.0,
    'cystathione_gamma_synthetase': 1.0,
    'Methionine_synthase': 1.0,
    'Phosphofructokinase': 1.0,
    'Branchedchain_amino_acid_transaminase': 1.0
}

data_pseudomonas = {
    'Acetylornithine_aminotransferase': 38.0,
    'dihydropicolinate_synthase': 37.0,
    'Acetolactate_synthase_large': 36.0,
    'Aspartate_transaminase': 36.0,
    'Acetolactate_synthase_large_subunit': 35.0,
    'Glutamine_synthetase': 33.0,
    'Dihydroxiacid_dehydratase': 32.0,
    '3isopropylmalate_dehydrogenase': 29.0,
    'diaminopimelate_decarboxylase': 22.0,
    'glutamate_synthase': 15.0,
    'isopropylmalate_isomerase_large_subunit': 15.0,
    'argininosuccinate_lyase': 14.0,
    'Threonine_synthase': 10.0,
    'glutamate_dehydrogenase': 10.0,
    'glycine_hydroxymethyltransferase': 9.0,
    'Cysteine_synthase': 9.0,
    'Glutamine_2_oxoglutarate_aminotransferase': 9.0,
    'Ornithine_carbamoyltransferase': 8.0,
    'Acetylglutamate_kinase': 7.0,
    'imidazole_glycerol_phosphate_synthase_H': 6.0,
    'ribosephosphate_pyrophosphokinase': 5.0,
    'Anthranilate_synthase_component_1': 5.0,
    'fumarate_hydratase': 4.0,
    'Glutamate_5_semialdehyde_dehydrogenase': 4.0,
    'fumarate_reductase_ironsulfur_subunit': 3.0,
    '3_dehydroquinate_synthase': 3.0,
    'phosphoribosyl_isomerase_A': 3.0,
    'Indole3glycerol_phosphate_synthase': 2.0,
    'enolase': 2.0,
    'Pyruvate_kinase': 2.0,
    'histidinol_dehydrogenase': 2.0,
    'N_acetyl_gamma_glutamyl_phosphate_reductase': 1.0,
    'Tryptophan_synthase_beta': 1.0,
    'Tryptophan_synthase_alpha': 1.0,
    'N_acetylglutamate_synthase': 1.0,
    'Citrate_synthase': 1.0
}

data_streptospo = {
    'dihydropicolinate_synthase': 138.0,
    'Aspartate_transaminase': 133.0,
    'cystathione_beta_lyase': 132.0,
    'succinyldiaminopimelate_transaminase': 131.0,
    'Asparagine_synthase': 129.0,
    'diaminopimelate_decarboxylase': 116.0,
    'Methionine_synthase': 115.0,
    'Threonine_synthase': 111.0,
    'cystathione_gamma_synthetase': 109.0,
    'Acetolactate_synthase_large_subunit': 101.0,
    'Phosphoglycerate_dehydrogenase': 97.0,
    'Acetylornithine_aminotransferase': 96.0,
    'Glucose_kinase': 95.0,
    'Aspartate_amino_transferase': 94.0,
    'Glutamine_synthetase': 80.0,
    'Homoserine_O_succinyltransferase': 80.0,
    'Dihydroxiacid_dehydratase': 79.0,
    'Tetrahydrodipicolinate_N_succinyl_transferase': 77.0,
    'Threonine_ammonialiase': 77.0,
    'Cysteine_synthase': 72.0,
    'Glucose_6_phosphate_dehydrogenase': 70.0,
    'Anthranilate_synthase_component_1': 69.0,
    'glycine_hydroxymethyltransferase': 68.0,
    'Succinate_dehydrogenase_flavoprotein': 65.0,
    'diaminopimelate_epimerase': 62.0,
    'dihydrolipoamide_acetyltransferase': 62.0,
    'Tryptophan_synthase_beta': 62.0,
    'Prephenate_dehydrogenase': 59.0,
    'Shikimate_dehydrogenase': 59.0,
    'Aconitate_hydratase': 59.0,
    '3isopropylmalate_dehydrogenase': 58.0,
    'Phosphofructokinase': 57.0,
    'transketolaseA': 57.0,
    'glyceraldehyde3phosphate_dehydrogenase': 56.0,
    'Isopropyl_malate_synthase': 55.0,
    'Anthranilate_phosphoribosyltransferase': 54.0,
    'glutamate': 54.0,
    'Ornithine_carbamoyltransferase': 51.0,
    '2_dehydro_3_deoxyphosphoheptonate_aldolase': 50.0,
    'Chorismate_synthase': 50.0,
    'Alanine_dehydrogenase': 49.0,
    'phosphogluconate_dehydrogenase': 49.0,
    'Glutamine_2-oxoglutarate': 48.0,
    'Branchedchain_amino_acid_transaminase': 47.0,
    'Aspartate_kinase': 43.0,
    'Argininosuccinate': 43.0,
    'Glucose_6_phosphate_isomerase': 43.0,
    'Homoserine_kinase': 44.0,
    'Tryptophan_synthase_alpha': 44.0,
    'fumarate_reductase_ironsulfur_subunit': 43.0,
    'succinyl_diaminopimelate_desuccinylase': 43.0,
    'fumarate_hydratase': 43.0,
    'Homoserine_dehydrogenase': 43.0,
    '3_phosphoshikimate_1carboxyvinyltransferase': 43.0,
    'Chorismate_mutase': 42.0,
    'glutamate_synthase': 42.0,
    'Citrate_synthase': 42.0,
    'Phosphoribosyl_isomerase': 41.0,
    'N-acetyl-gamma-glutamyl-phosphate_reductase': 41.0,
    'phosphoglycerate_mutase': 41.0,
    'argininosuccinate_lyase': 41.0,
    'dihydropicolinate_reductase': 40.0,
    'histidinolphosphate_aminotransferase': 40.0,
    'Prephenate_dehydratase': 39.0,
    'phosphoribosylanthranilate_isomerase': 39.0,
    'phosphoglycerate_kinase': 39.0,
    'Shikimate_kinase': 38.0,
    'Aspartate_semialdehyde_dehydrogenase': 38.0,
    'succinylCoA_synthetase_subunit_alpha': 37.0,
    'isopropylmalate_isomerase_large_subunit': 36.0,
    'Glutamate_5_kinase': 36.0,
    'Glutamate-5-semialdehyde_dehydrogenase': 35.0,
    'enolase': 34.0,
    'Ribose_5_phosphate_isomerase': 34.0,
    'succinylCoA_synthetase_subunit_beta': 34.0,
    'ribosephosphate_pyrophosphokinase': 34.0,
    '3_dehydroquinate_synthase': 33.0,
    'Phosphoserine_Phosphatase': 32.0,
    'Pyrroline-5-carboxylate_reductase': 31.0,
    'isopropylmalate_isomerase_small_subunit': 30.0,
    'Ketoacid_reductoisomerase': 29.0,
    '3_dehydroquinate_dehydratase': 27.0,
    'Acetylglutamate_kinase': 25.0,
    'Glutamate_N-acetyltransferase': 24.0,
    'N-acetylglutamate_synthase': 24.0,
    'ATP_phosphoribosyltransferase': 24.0,
    'transaldolase': 24.0,
    'transketolase': 24.0,
    'alphaketoglutarate_decarboxylase': 23.0,
    'Ribulose_phosphate_3_epimerase': 21.0,
    'Triosephosphate_isomerase': 20.0,
    'Fructose_biphosphate_aldolase': 20.0,
    'malate_dehydrogenase': 20.0,
    'bifunctional_indole3glycerol_phosphate_synthase_phosphoribosylanthranilate_isomerase': 20.0,
    'Isocitrate_dehydrogenase': 19.0,
    'Phosphoserine_aminotransferase': 19.0,
    'histidinol_dehydrogenase': 18.0,
    'Indole3glycerol_phosphate_synthase': 18.0,
    '6_phosphogluconolactonase': 17.0,
    'serine_O_acetyltransferase': 17.0,
    'histidinol_phosphatase': 17.0,
    'imidazole_glycerol_phosphate_synthase_H': 16.0,
    'imidazoleglycerol_phosphate_dehydratase': 15.0,
    'Pyruvate_kinase': 14.0,
    'phosphoribosyl_isomerase_A': 13.0,
    'phosphoribosyl_ATP_diphosphatase': 11.0,
    'phosphoribosyl_AMP_cyclohydrolase': 10.0
}

# Convertir los datos a DataFrames
df_cyanobacteria = pd.DataFrame(list(data_cyanobacteria.items()), columns=['Protein', 'Count'])
df_ornithinimicrobiaceae = pd.DataFrame(list(data_ornithinimicrobiaceae.items()), columns=['Protein', 'Count'])
df_pseudomonas = pd.DataFrame(list(data_pseudomonas.items()), columns=['Protein', 'Count'])
df_streptospo = pd.DataFrame(list(data_streptospo.items()), columns=['Protein', 'Count'])

# Crear la gráfica de barras comparativa
fig, ax = plt.subplots(figsize=(12, 8))

ax.bar(df_cyanobacteria['Protein'], df_cyanobacteria['Count'], label='Cyanobacteria', alpha=0.6, width=0.4, align='center')
ax.bar(df_ornithinimicrobiaceae['Protein'], df_ornithinimicrobiaceae['Count'], label='Ornithinimicrobiaceae', alpha=0.6, width=0.4, align='edge')
ax.bar(df_pseudomonas['Protein'], df_pseudomonas['Count'],

In [269]:
df_cyanobacteria=pd.read_csv('2.csv',index_col=0)
df_cyanobacteria.sort_values('conteo',ascending=False)
df_ornithinimicrobiaceae=pd.read_csv('1.csv',index_col=0)
df_ornithinimicrobiaceae.sort_values('conteo',ascending=False)
df_pseudomonas=pd.read_csv('3.csv',index_col=0)
df_pseudomonas.sort_values('conteo',ascending=False)
df_streptosporangium=df_count_genes_participation.copy(deep=True)
conteso=[df_cyanobacteria,df_ornithinimicrobiaceae,df_pseudomonas]

In [292]:
import matplotlib.pyplot as plt
import pandas as pd

# Supongo que ya tienes los tres DataFrames df_cyanobacteria, df_pseudomonas y df_ornithinimicrobiaceae
# Asegúrate de que tengan la estructura mencionada (índice como genes y una columna "conteo")

# Añadimos una columna para indicar el linaje bacteriano
df_cyanobacteria['linaje'] = 'Cyanobacteriota'
df_pseudomonas['linaje'] = 'Pseudomonas'
df_ornithinimicrobiaceae['linaje'] = 'Ornithinimicrobiaceae'

# Concatenamos los DataFrames en uno solo
df_combined = pd.concat([df_cyanobacteria[['conteo', 'linaje','ruta']],df_ornithinimicrobiaceae[['conteo', 'linaje','ruta']],
                         df_pseudomonas[['conteo', 'linaje','ruta']]])

# Reseteamos el índice para tener los genes como una columna
df_combined.reset_index(inplace=True)
df_combined.rename(columns={'index': 'gen', 'conteo': 'conteo'}, inplace=True)
df_combined['color']=0
df_combined['color'][df_combined['linaje']=='Cyanobacteriota']='#4C72B0'
df_combined['color'][df_combined['linaje']=='Ornithinimicrobiaceae']='#FF8C00'
df_combined['color'][df_combined['linaje']=='Pseudomonas']='#2CA02C'

# Ahora graficamos
plt.figure(figsize=(14, 9))  # Ajustamos el tamaño de la figura

# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for linaje, color in zip(['Cyanobacteriota','Ornithinimicrobiaceae', 'Pseudomonas'], ['#4C72B0', '#FF8C00', '#2CA02C']):
    for ruta_met in 
    subset = df_combined[df_combined['linaje'] == linaje]
    plt.scatter(subset['gen'], subset['conteo'], label=linaje, color=color)

for ruta_metabolica in df_combined['ruta'].unique():
    subset = df_combined[df_combined['ruta']==ruta_metabolica]
    plt.scatter(subset['gen'],subset['conteo'],label=subset['linaje'],color=subset['color'])


# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42,top=1,right=1,left=0)  # Ajustar el margen inferior

# Mostrar el gráfico
plt.show()
#plt.savefig('a.png')
plt.savefig('pseu_cyano_orin_genes.svg',format='svg')

/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
for ruta_metabolica in df_combined['linaje'].unique():
    df_combined['color'][df_combined]

In [300]:
del plt

In [326]:
import matplotlib.pyplot as plt
# Ahora graficamos
plt.figure(figsize=(14, 9))  # Ajustamos el tamaño de la figura

df_combined.sort_values(by='ruta',inplace=True)
# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for i in df_combined.index:
    plt.scatter(df_combined.loc[i,'gen'],df_combined.loc[i,'conteo'],label=df_combined.loc[i,'linaje'],color=df_combined.loc[i,'color'])
    


# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42,top=1,right=1,left=0.02)  # Ajustar el margen inferior

# Mostrar el gráfico
plt.show()
#plt.savefig('a.png')
plt.savefig('pseu_cyano_orin_genes.svg',format='svg')

In [320]:
del plt

In [347]:
import matplotlib.pyplot as plt

# Ahora graficamos
plt.figure(figsize=(14, 9))  # Ajustamos el tamaño de la figura

df_combined.sort_values(by='ruta', inplace=True)

# Usamos un set para evitar duplicados en la leyenda
legend_labels = set()

# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for i in df_combined.index:
    linaje = df_combined.loc[i, 'linaje']
    
    # Solo agregamos una entrada a la leyenda si no ha sido agregada antes
    if linaje not in legend_labels:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    label=linaje, color=df_combined.loc[i, 'color'])
        legend_labels.add(linaje)  # Añadimos el linaje al set de leyendas

    else:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    color=df_combined.loc[i, 'color'])  # No repetimos la etiqueta de la leyenda

# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42, top=1, right=1, left=0.035) # Ajustar el margen inferior

# Ajustamos los límites de los ejes para reducir espacio alrededor de los datos
#plt.xlim((0,0.1))  # Ajustar límites eje X
#plt.ylim((0,0.1))  # Ajustar límites eje Y

plt.xlim(right=66)  # adjust the right leaving left unchanged
plt.xlim(left=-1)

# Ajustar el aspecto de la gráfica para aprovechar mejor el espacio
#plt.gca().set_aspect('auto', adjustable='box')  # Cambiar el aspecto de la gráfica si es necesario

# Mostrar el gráfico


# Guardamos la imagen
plt.savefig('pseu_cyano_orin_genes.svg', format='svg')

In [351]:
import matplotlib.pyplot as plt
import numpy as np

# Ahora graficamos
plt.figure(figsize=(14, 9))  # Ajustamos el tamaño de la figura

df_combined.sort_values(by='ruta', inplace=True)

# Usamos un set para evitar duplicados en la leyenda
legend_labels = set()

# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for i in df_combined.index:
    linaje = df_combined.loc[i, 'linaje']
    
    # Solo agregamos una entrada a la leyenda si no ha sido agregada antes
    if linaje not in legend_labels:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    label=linaje, color=df_combined.loc[i, 'color'])
        legend_labels.add(linaje)  # Añadimos el linaje al set de leyendas
    else:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    color=df_combined.loc[i, 'color'])  # No repetimos la etiqueta de la leyenda

# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42, top=1, right=1, left=0.035) # Ajustar el margen inferior

# Ajustamos los límites de los ejes para reducir espacio alrededor de los datos
plt.xlim(right=66)  # adjust the right leaving left unchanged
plt.xlim(left=-1)

# Añadir las llaves para los genes
# Aquí tomamos como ejemplo que los genes 10 a 15 forman un grupo
plt.plot([10, 15], [50, 50], color='black', lw=2)  # Dibuja la llave en el eje y=50 entre los genes 10 a 15
plt.text(12.5, 55, 'Grupo 1', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

# Otro ejemplo, genes 20 a 25
plt.plot([20, 25], [60, 60], color='black', lw=2)  # Llave entre genes 20 a 25
plt.text(22.5, 65, 'Grupo 2', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

# Mostrar el gráfico
plt.show()

# Guardamos la imagen
plt.savefig('pseu_cyano_orin_genes_with_brackets.svg', format='svg')

In [352]:
import matplotlib.pyplot as plt
import numpy as np

# Ahora graficamos
plt.figure(figsize=(14, 9))  # Ajustamos el tamaño de la figura

df_combined.sort_values(by='ruta', inplace=True)

# Usamos un set para evitar duplicados en la leyenda
legend_labels = set()

# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for i in df_combined.index:
    linaje = df_combined.loc[i, 'linaje']
    
    # Solo agregamos una entrada a la leyenda si no ha sido agregada antes
    if linaje not in legend_labels:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    label=linaje, color=df_combined.loc[i, 'color'])
        legend_labels.add(linaje)  # Añadimos el linaje al set de leyendas
    else:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    color=df_combined.loc[i, 'color'])  # No repetimos la etiqueta de la leyenda

# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42, top=1, right=1, left=0.035) # Ajustar el margen inferior

# Ajustamos los límites de los ejes para reducir espacio alrededor de los datos
plt.xlim(right=66)  # adjust the right leaving left unchanged
plt.xlim(left=-1)

# Añadir las llaves para los genes fuera del cuadro
# Aquí tomamos como ejemplo que los genes 10 a 15 forman un grupo, pero fuera del gráfico

# Dibujar la llave fuera del gráfico, por ejemplo, a y=80 (más alto que el rango de los puntos)
plt.plot([10, 15], [80, 80], color='black', lw=2)  # Llave horizontal fuera del gráfico
plt.text(12.5, 85, 'Grupo 1', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

# Otro ejemplo, genes 20 a 25, también fuera del gráfico
plt.plot([20, 25], [85, 85], color='black', lw=2)  # Llave horizontal fuera del gráfico
plt.text(22.5, 90, 'Grupo 2', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

# Mostrar el gráfico
plt.show()

# Guardamos la imagen
plt.savefig('pseu_cyano_orin_genes_with_brackets_outside.svg', format='svg')

In [430]:
import matplotlib.pyplot as plt
import numpy as np

# Ahora graficamos
plt.figure(figsize=(14, 10))  # Ajustamos el tamaño de la figura

df_combined.sort_values(by='ruta', inplace=True)

# Usamos un set para evitar duplicados en la leyenda
legend_labels = set()

# Usamos un scatter plot, donde los puntos estarán coloreados por linaje
for i in df_combined.index:
    linaje = df_combined.loc[i, 'linaje']
    
    # Solo agregamos una entrada a la leyenda si no ha sido agregada antes
    if linaje not in legend_labels:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    label=linaje, color=df_combined.loc[i, 'color'])
        legend_labels.add(linaje)  # Añadimos el linaje al set de leyendas
    else:
        plt.scatter(df_combined.loc[i, 'gen'], df_combined.loc[i, 'conteo'],
                    color=df_combined.loc[i, 'color'])  # No repetimos la etiqueta de la leyenda

# Configuraciones del gráfico
plt.xlabel('Genes')
plt.ylabel('Conteo')

plt.xticks(rotation=90)  # Rotar las etiquetas del eje X a 43 grados
plt.legend(title='Linaje Bacteriano')

# Activamos el grid y lo configuramos para que sea punteado
plt.grid(True, linestyle='--', color='grey')  # Las líneas del grid serán punteadas

# Ajustamos los márgenes para que todo se vea bien
plt.subplots_adjust(bottom=0.42, top=0.93, right=1, left=0.035) # Ajustar el margen inferior

# Ajustamos los límites de los ejes para reducir espacio alrededor de los datos
plt.xlim(right=66)  # adjust the right leaving left unchanged
plt.xlim(left=-1)

# Función para dibujar el estilo /\ (triangular)
def dibujar_triangulo(x_start, x_end, y, direccion="arriba"):
    """
    Dibuja un triángulo estilo /\ entre x_start y x_end a una altura y.
    """
    if direccion == "arriba":
        # Dibujamos las dos líneas diagonales que forman el triángulo
        plt.plot([x_start, (x_start + x_end) / 2], [y, y + 2], color='black', lw=2)  # Lado izquierdo
        plt.plot([x_end, (x_start + x_end) / 2], [y, y + 2], color='black', lw=2)  # Lado derecho

    else:
        # Dibujar el triángulo hacia abajo
        plt.plot([x_start, (x_start + x_end) / 2], [y, y - 10], color='black', lw=2)  # Lado izquierdo
        plt.plot([x_end, (x_start + x_end) / 2], [y, y - 10], color='black', lw=2)  # Lado derecho
        plt.plot([x_start, x_end], [y, y], color='black', lw=2)  # Base del triángulo

# Dibujar triángulos y nombres
# Aquí tomamos como ejemplo que los genes 10 a 15 forman un grupo
dibujar_triangulo(0, 2, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text(1, 45.5, '3PGA_AMINOACID', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(3, 15, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((15+3)/2, 45.5, 'ALPHAKETOGLUTARATE_AMINOACIDS', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(16, 22, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((16+22)/2, 45.5, 'E4P_AMINO_ACIDS', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(23, 28, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((23+28)/2, 45.5, 'Glycolysis', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(29, 39, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((29+39)/2, 45.5, 'OXALACETATE_AMINOACIDS', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(40, 43, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((40+43)/2, 45.5, 'PPP', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(44, 53, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((44+53)/2, 45.5, 'PYR_THR_AA', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(54, 61, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((54+61)/2, 45.5, 'R5P_AMINOACIDS', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

dibujar_triangulo(62, 65, 43, direccion="arriba")  # Triángulo arriba entre genes 10 y 15
plt.text((62+65)/2, 45.5, 'TCA', horizontalalignment='center', verticalalignment='bottom', fontsize=10)

# Mostrar el gráfico
plt.show()

# Guardamos la imagen
plt.savefig('pseu_cyano_orin_genes_with_triangles.svg', format='svg')

In [426]:
45.5-43

2.5

In [425]:
df_combined.max()

gen         succinyldiaminopimelate_transaminase
conteo                                      42.0
linaje                               Pseudomonas
ruta                                         TCA
color                                    #FF8C00
ruta_num                                       0
dtype: object

In [435]:
df_combined[df_combined['conteo']==42.0]

,gen,conteo,linaje,ruta,color,ruta_num
36,Acetylornithine_aminotransferase,42.0,Cyanobacteriota,ALPHAKETOGLUTARATE_AMINOACIDS,#4C72B0,0

In [439]:
'ALPHAKETOGLUTARATE_AMINOACIDS'.lower()

'alphaketoglutarate_aminoacids'

In [422]:
pib[pib['ruta']=='TCA']

                                      gen ruta  ruta_num
62                       Citrate_synthase  TCA         0
63                     fumarate_hydratase  TCA         0
64                    Aconitate_hydratase  TCA         0
65  fumarate_reductase_ironsulfur_subunit  TCA         0

In [405]:
pib=df_combined.drop(columns=['conteo','linaje','color'])

In [408]:
pib=pib.drop_duplicates().reset_index(drop=True)

In [395]:
df_combined.reset_index()

,index,gen,conteo,linaje,ruta,color,ruta_num
0,13,Cysteine_synthase,7.0,Cyanobacteriota,3PGA_AMINOACIDS,#4C72B0,0
1,70,Cysteine_synthase,1.0,Ornithinimicrobiaceae,3PGA_AMINOACIDS,#FF8C00,0
2,69,Phosphoglycerate_dehydrogenase,1.0,Ornithinimicrobiaceae,3PGA_AMINOACIDS,#FF8C00,0
3,68,glycine_hydroxymethyltransferase,1.0,Ornithinimicrobiaceae,3PGA_AMINOACIDS,#FF8C00,0
4,110,Cysteine_synthase,9.0,Pseudomonas,3PGA_AMINOACIDS,#2CA02C,0
...,...,...,...,...,...,...,...
111,97,fumarate_reductase_ironsulfur_subunit,3.0,Pseudomonas,TCA,#2CA02C,0
112,61,Citrate_synthase,1.0,Ornithinimicrobiaceae,TCA,#FF8C00,0
113,98,Citrate_synthase,1.0,Pseudomonas,TCA,#2CA02C,0
114,96,fumarate_hydratase,4.0,Pseudomonas,TCA,#2CA02C,0
115,0,fumarate_hydratase,4.0,Cyanobacteriota,TCA,#4C72B0,0

In [ ]:
df_combined['gen'].uniq

In [350]:
df_combined['ruta'].unique()

array(['3PGA_AMINOACIDS', 'ALPHAKETOGLUTARATE_AMINOACIDS',
       'E4P_AMINO_ACIDS', 'Glycolysis', 'OXALACETATE_AMINOACIDS', 'PPP',
       'PYR_THR_AA', 'R5P_AMINOACIDS', 'TCA'], dtype=object)

In [397]:
len(df_combined['gen'].unique())

66

In [287]:
df_combined['color'][df_combined['linaje']=='Cyanobacteriota']='#4C72B0'
df_combined['color'][df_combined['linaje']=='Ornithinimicrobiaceae']='#FF8C00'
df_combined['color'][df_combined['linaje']=='Pseudomonas']='#2CA02C'

/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/envs/TDA/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
df_combined['color'][df_combined['Pseudomonas']=='Ornithinimicrobiaceae']='#2CA02C'

In [290]:
df_combined['color'][df_combined['linaje']=='Ornithinimicrobiaceae']

70    #FF8C00
69    #FF8C00
68    #FF8C00
57    #FF8C00
58    #FF8C00
59    #FF8C00
42    #FF8C00
43    #FF8C00
44    #FF8C00
52    #FF8C00
51    #FF8C00
50    #FF8C00
49    #FF8C00
48    #FF8C00
47    #FF8C00
46    #FF8C00
45    #FF8C00
56    #FF8C00
55    #FF8C00
54    #FF8C00
53    #FF8C00
79    #FF8C00
77    #FF8C00
71    #FF8C00
72    #FF8C00
74    #FF8C00
73    #FF8C00
76    #FF8C00
75    #FF8C00
78    #FF8C00
64    #FF8C00
63    #FF8C00
65    #FF8C00
66    #FF8C00
67    #FF8C00
61    #FF8C00
62    #FF8C00
60    #FF8C00
Name: color, dtype: object

In [281]:
df_combined['ruta'].unique()

array(['3PGA_AMINOACIDS', 'ALPHAKETOGLUTARATE_AMINOACIDS',
       'E4P_AMINO_ACIDS', 'Glycolysis', 'OXALACETATE_AMINOACIDS', 'PPP',
       'PYR_THR_AA', 'R5P_AMINOACIDS', 'TCA'], dtype=object)

In [11]:
traduced_df(df_pathway_make_hole['R5P_AMINOACIDS'][0],names)

,ribosephosphate_pyrophosphokinase,imidazoleglycerol_phosphate_dehydratase,phosphoribosyl_AMP_cyclohydrolase,histidinolphosphate_aminotransferase,phosphoribosyl_isomerase_A,histidinol_dehydrogenase,ATP_phosphoribosyltransferase,histidinol_phosphatase,imidazole_glycerol_phosphate_synthase_H
R5P_AMINOACIDS,,,,,,,,,
Serinicoccus sp. CNJ-927 CNJ-927,1.0,1.0,1.0,1.0,2,1.0,0.0,1.0,1.0
Ornithinimicrobium sp. na,0.0,1.0,0.0,1.0,2,1.0,0.0,1.0,2.0
Ornithinimicrobium humiphilum DSM 12362,1.0,1.0,0.0,2.0,2,1.0,1.0,1.0,2.0
Serinicoccus chungangensis CD08_5,1.0,1.0,1.0,2.0,2,1.0,1.0,1.0,2.0

<h2>Se buscan uno hoyos pero al separar por genero y ruta metabólica</h2>

In [12]:
df_by_genus_pathway,df_by_genus_pathway_drop_duplicate,representative_genomes_genus_pathway=get_df_by_genus_pathway(df_by_pathway,names)
complex_genus_pathways=get_complex_by_pathways(df_by_genus_pathway_drop_duplicate)

In [13]:
traduced_df(df_by_genus_pathway['Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS'],names)

,Ornithine_carbamoyltransferase,Glutamate_5_kinase,Glutamate-5-semialdehyde_dehydrogenase,Pyrroline-5-carboxylate_reductase,Acetylornithine_aminotransferase,Glutamine_2-oxoglutarate,glutamate,argininosuccinate_lyase,Argininosuccinate,glutamate_synthase,Glutamine_synthetase
Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS,,,,,,,,,,,
Serinicoccus chungangensis CD08_5,1.0,1.0,1.0,1.0,6.0,1.0,0.0,1.0,1.0,1.0,3
Serinicoccus hydrothermalis JLT9,1.0,1.0,1.0,1.0,8.0,1.0,0.0,1.0,1.0,2.0,3
Serinicoccus sp. CUA-874 CUA-874,1.0,1.0,1.0,1.0,5.0,1.0,0.0,1.0,1.0,1.0,4
Serinicoccus sp. CNJ-927 CNJ-927,1.0,0.0,1.0,1.0,7.0,1.0,0.0,1.0,1.0,1.0,4

In [14]:
holes_genus_no_names,holes_genus_with_names,holes_genus_per_filt_lvl=get_holes_by_pathways(complex_genus_pathways,df_by_genus_pathway_drop_duplicate)

se buscan ciclos en el tiempo 3.0 para Ornithinimicrobium_3PGA_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [15, 10, 6, 1] en el tiempo 1.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
Se encontró el ciclo [15, 4, 2, 1] en el tiempo 1.0 para Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Ornithinimicrobium_PPP
Se encontró el ciclo [11, 3, 5, 2] en el tiempo 1.0 para Ornithinimicrobium_PPP
Se encontró el ciclo [10, 1, 5, 2] en el tiempo 2.0 para Ornithinimicrobium_3PGA_AMINOACIDS
se buscan ciclos en el tiempo 6.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS
Se encontró el ciclo [0, 14, 16, 2] en el tiempo 5.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS
Se encontró el ciclo [4, 7, 5, 2] en el tiempo 5.0 para Ornithinimicrobium_OXALACETATE_AMINOACIDS

In [16]:
resum_genus=get_resum_df(df_by_genus_pathway,representative_genomes_genus_pathway,names,complex_genus_pathways,holes_genus_with_names)
resum_genus

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
Serinicoccus_3PGA_AMINOACIDS,5,0,[],[],[]
Ornithinimicrobium_3PGA_AMINOACIDS,5,1,"[[Ornithinimicrobium sp. na, Ornithinimicrobiu...","[[Ornithinimicrobium, Ornithinimicrobium, [Orn...",[1.0]
Serinicoccus_E4P_AMINO_ACIDS,17,0,[],[],[]
Ornithinimicrobium_E4P_AMINO_ACIDS,17,0,[],[],[]
Serinicoccus_TCA,11,0,[],[],[]
Ornithinimicrobium_TCA,11,0,[],[],[]
Serinicoccus_ALPHAKETOGLUTARATE_AMINOACIDS,11,0,[],[],[]
Ornithinimicrobium_ALPHAKETOGLUTARATE_AMINOACIDS,11,2,"[[Ornithinimicrobium cerasi USBA17B2, Ornithin...","[[Ornithinimicrobium, Ornithinimicrobium, Orni...",[1.0]
Serinicoccus_R5P_AMINOACIDS,9,0,[],[],[]
Ornithinimicrobium_R5P_AMINOACIDS,9,0,[],[],[]
Serinicoccus_﻿Glycolysis,1,0,[],[],[]
Ornithinimicrobium_﻿Glycolysis,1,0,[],[],[]
Serinicoccus_PPP,8,0,[],[],[]
Ornithinimicrobium_PPP,8,1,"[[Ornithinimicrobium cerasi USBA17B2, [Ornithi...","[[Ornithinimicrobium, [Ornithinimicrobium, Orn...",[1.0]
Serinicoccus_Glycolysis,10,0,[],[],[]
Ornithinimicrobium_Glycolysis,10,0,[],[],[]
Serinicoccus_OXALACETATE_AMINOACIDS,16,0,[],[],[]
Ornithinimicrobium_OXALACETATE_AMINOACIDS,16,2,"[[Ornithinimicrobium pratense W204, Ornithinim...","[[Ornithinimicrobium, Ornithinimicrobium, Orni...",[1.0]
Serinicoccus_PYR_THR_AA,10,0,[],[],[]
Ornithinimicrobium_PYR_THR_AA,10,0,[],[],[]

<h1>Para obtener la información de los 1-hoyos de la ruta R5P AMINOACIDS:</h1>

In [13]:
R5P_df_by_pathway={'R5P_AMINOACIDS':df_by_pathway['R5P_AMINOACIDS']}
R5P_df_by_pathway_drop_duplicate={'R5P_AMINOACIDS':df_by_pathway_drop_duplicate['R5P_AMINOACIDS']}
R5P_representative_genomes={'R5P_AMINOACIDS':representative_genomes['R5P_AMINOACIDS']}
R5P_complex_pathways={'R5P_AMINOACIDS':complex_pathways['R5P_AMINOACIDS']}

In [14]:
R5P_holes_no_names,R5P_holes_with_names,R5P_holes_per_filt_lvl=get_holes_by_pathways(R5P_complex_pathways,R5P_df_by_pathway_drop_duplicate)

se buscan ciclos en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [10, 25, 7, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [46, 33, 7, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [14, 13, 6, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [111, 41, 99, 57] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [99, 78, 66, 57] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [11, 4, 7, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [57, 99, 54, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [18, 21, 7, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [103, 99, 54, 26] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [78, 99, 60, 35] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 96, 23, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [50, 44, 23, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [14, 4, 7, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [12, 25, 7, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 26, 18, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 1, 7, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [36, 39, 25, 4] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [10, 40, 5, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [11, 13, 6, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [91, 92, 73, 66] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [91, 66, 57, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [4, 52, 1, 7] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [101, 60, 99, 54] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [22, 0, 7, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [46, 28, 14, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [18, 38, 14, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 101, 14, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [52, 53, 49, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [27, 21, 7, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [101, 60, 94, 52] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [61, 1, 7, 0] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [50, 16, 14, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 96, 15, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [21, 49, 1, 7] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 101, 52, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 26, 49, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [124, 114, 91, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [33, 51, 21, 7] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [22, 6, 5, 2] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [57, 94, 52, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [57, 111, 34, 87, 95, 61, 1] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [54, 55, 29, 5] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [109, 79, 89, 74] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [89, 117, 63, 74] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [140, 117, 89, 102] en el tiempo 1.0 para R5P_AMINOACIDS
Se encontró el ciclo [146, 63, 117, 140] en el tiempo 1.0 para R5P_AMINOACIDS
se buscan ciclos en el tiempo 3.0 para R5P_AMINOACIDS
Se encontró el ciclo [128, 48, 54, 49] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [99, 30, 106, 48, 54] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [149, 30, 99, 57] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [73, 98, 108, 86, 79, 151, 32] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [131, 97, 117, 74] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [59, 156, 87, 1] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [31, 87, 1, 2] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [141, 151, 139, 80] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [110, 157, 20, 15] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [144, 116, 84, 87] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [105, 135, 84, 87] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [89, 140, 133, 106, 71] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [100, 91, 92, 77] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [129, 64, 138, 1] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [76, 68, 59, 54] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [64, 129, 144, 116] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [138, 64, 90, 93, 133, 106, 48, 54] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [79, 102, 115, 132, 126, 30, 71] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [146, 113, 141, 151, 63] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [124, 126, 132, 62, 1] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [141, 151, 79, 71] en el tiempo 2.0 para R5P_AMINOACIDS
Se encontró el ciclo [124, 126, 30, 99] en el tiempo 2.0 para R5P_AMINOACIDS
se buscan ciclos en el tiempo 4.0 para R5P_AMINOACIDS
Se encontró el ciclo [153, 85, 64, 93] en el tiempo 3.0 para R5P_AMINOACIDS
Se encontró el ciclo [88, 142, 108, 73] en el tiempo 3.0 para R5P_AMINOACIDS
Se encontró el ciclo [108, 142, 105, 16] en el tiempo 3.0 para R5P_AMINOACIDS

In [15]:
get_resum_df(R5P_df_by_pathway,R5P_representative_genomes,names,R5P_complex_pathways,R5P_holes_with_names)

/opt/conda/envs/TDA/lib/python3.7/site-packages/pandas/core/internals/blocks.py:937: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_value = np.asarray(value)

,num_columnas,num_hoyos,ciclos,ciclos por genero,duración hoyos
R5P_AMINOACIDS,10,71,[[Streptosporangiaceae bacterium SHSU.bins.512...,"[[Streptosporangiaceae, Streptosporangiaceae, ...",[1.0]

<h3>Género por R5P</h3>

In [19]:
R5P_df_by_genus_pathway,R5P_df_by_genus_pathway_drop_duplicate,R5P_representative_genomes_genus_pathway=get_df_by_genus_pathway(R5P_df_by_pathway,names)
R5P_complex_genus_pathways=get_complex_by_pathways(R5P_df_by_genus_pathway_drop_duplicate)

In [20]:
R5P_holes_genus_no_names,R5P_holes_genus_with_names,R5P_holes_genus_per_filt_lvl=get_holes_by_pathways(R5P_complex_genus_pathways,R5P_df_by_genus_pathway_drop_duplicate)

se buscan ciclos en el tiempo 2.0 para Streptosporangium_R5P_AMINOACIDS
Se encontró el ciclo [9, 3, 1, 0] en el tiempo 1.0 para Streptosporangium_R5P_AMINOACIDS
Se encontró el ciclo [4, 7, 3, 1] en el tiempo 1.0 para Streptosporangium_R5P_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Nonomuraea_R5P_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Microbispora_R5P_AMINOACIDS
Se encontró el ciclo [10, 2, 7, 3] en el tiempo 1.0 para Microbispora_R5P_AMINOACIDS
Se encontró el ciclo [5, 10, 2, 1] en el tiempo 1.0 para Nonomuraea_R5P_AMINOACIDS
Se encontró el ciclo [14, 18, 5, 1] en el tiempo 1.0 para Nonomuraea_R5P_AMINOACIDS
Se encontró el ciclo [7, 2, 1, 0] en el tiempo 1.0 para Nonomuraea_R5P_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Acrocarpospora_R5P_AMINOACIDS
Se encontró el ciclo [4, 2, 1, 0] en el tiempo 1.0 para Acrocarpospora_R5P_AMINOACIDS
se buscan ciclos en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [43, 44, 24, 17] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [53, 11, 51, 6] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [63, 27, 51, 8] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [51, 30, 17, 8] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [53, 11, 46, 4] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [76, 66, 43, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [8, 51, 6, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [6, 53, 4, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [43, 17, 8, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [4, 5, 3, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [8, 46, 4, 1] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [41, 25, 14, 69] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [31, 61, 25, 41] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [92, 69, 14, 98] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [92, 54, 41, 69] en el tiempo 1.0 para Streptosporangiaceae_R5P_AMINOACIDS
se buscan ciclos en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [76, 78, 58, 2, 6] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [6, 2, 58, 22, 93, 17, 1] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [41, 92, 85, 58, 22] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [81, 15, 90, 1] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [28, 19, 10, 6] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [50, 60, 38, 31, 22, 93, 24] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [76, 78, 84, 13, 1] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [80, 2, 6, 3] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [31, 54, 67, 84, 78, 58, 22] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [96, 68, 36, 39] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [93, 103, 91, 32] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [15, 81, 96, 68] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [98, 65, 93, 103, 14] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [57, 87, 36, 39] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [83, 49, 69, 25] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [90, 15, 42, 45, 85, 58, 2, 6] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [93, 103, 31, 22] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [52, 43, 44, 29] en el tiempo 2.0 para Streptosporangiaceae_R5P_AMINOACIDS
se buscan ciclos en el tiempo 4.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [105, 37, 15, 45] en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [40, 94, 60, 24] en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [57, 70, 10, 6] en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [101, 35, 27, 1] en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS
Se encontró el ciclo [58, 71, 39, 1] en el tiempo 3.0 para Streptosporangiaceae_R5P_AMINOACIDS

In [21]:
get_resum_df(R5P_df_by_genus_pathway,R5P_representative_genomes_genus_pathway,names,R5P_complex_genus_pathways,R5P_holes_genus_per_filt_lvl)

TypeError: 'float' object is not iterable